services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TOKEN}
    networks:
      - tunnel

  bricehomelab:
    container_name: brice-homelab
    image: bmo75/brice-homelab-build-counter:latest
    restart: unless-stopped
    networks:
      - tunnel

networks:
  tunnel:
    name: tunnel