export const factsForDuration = [
  "In just over 20 days, you could have walked from Paris to Berlin (approx. 1050 km, averaging 50km/day)!",
  "During this time (around 498 hours), the International Space Station would have orbited the Earth approximately 332 times!",
  "In about 3 weeks, you could have completed an intensive online course on a new skill.",
  "That's enough time to grow a batch of radishes from seed to harvest!",
  "You could have listened to the entire 'Harry Potter' audiobook series (approx. 117 hours) more than 4 times over!",
  "A dedicated team could build a small, habitable cabin in about 3 weeks.",
  "In 20 days, you could learn and memorize around 200-400 new vocabulary words in a foreign language.",
  "You could have binge-watched all seasons of 'Friends' (approx. 85 hours) almost 6 times.",
  "Enough time to write a short novella (around 20,000-30,000 words) if writing 1000-1500 words a day.",
  "You could have flown around the world (approx. 40,000 km at 900 km/h) about 11 times, not including layovers.",
  "A hen incubates her eggs for about 21 days before they hatch.",
  "You could have read 'War and Peace' (approx. 587,287 words) at an average reading speed multiple times.",
  "The Tour de France cycling race typically lasts for about 3 weeks.",
  "You could have knitted a complex sweater or a couple of simpler ones.",
  "Enough time to complete a 500-1000 piece jigsaw puzzle, or several smaller ones.",
  "You could have volunteered for approximately 20 full workdays at a local charity.",
  "A full-time student could complete a significant portion of a semester course in 3 weeks.",
  "You could have practiced a musical instrument for about 60-100 hours (2-3 hours/day).",
  "The average person sleeps for about 160 hours in 20 days (assuming 8 hours/night).",
  "You could have painted a moderately sized room, including prep work and multiple coats.",
  "Enough time to plan and take a short road trip across a few states or small countries.",
  "You could have learned the basics of a new programming language through online tutorials.",
  "A colony of ants can build a complex nest in a few weeks.",
  "You could have trained for and run a 5k race, even starting from a low fitness level.",
  "Enough time to thoroughly declutter and organize a large house.",
  "You could have watched all the extended editions of 'The Lord of the Rings' and 'The Hobbit' trilogies (approx. 21 hours) over 23 times.",
  "A caterpillar can transform into a butterfly in about 2-4 weeks, depending on the species.",
  "You could have learned to cook 20 new and complex recipes.",
  "Enough time to create a detailed scrapbook of memories.",
  "You could have planted and started a small vegetable garden.",
  "The Apollo 11 mission to the moon and back took about 8 days.",
  "You could have written and recorded a short song or EP.",
  "Enough time to learn a new board game thoroughly and play it multiple times.",
  "You could have taken a beginner's pottery class and created several pieces.",
  "A person could hike a significant section of a long-distance trail like the Appalachian Trail.",
  "You could have completed a deep dive into a historical period or event through books and documentaries.",
  "Enough time to build a complex Lego model, like the Millennium Falcon.",
  "You could have learned basic car maintenance skills, like changing oil or a tire.",
  "A dedicated birdwatcher could spot dozens of new species in a diverse habitat over 3 weeks.",
  "You could have written daily journal entries, amounting to a significant personal record.",
  "Enough time to learn and practice several magic tricks to a performance level.",
  "You could have created a series of digital art pieces or illustrations.",
  "A person could learn the basics of sign language (e.g., the alphabet and common phrases).",
  "You could have explored all the major museums in a large city.",
  "Enough time to research and write a comprehensive blog post or article series.",
  "You could have participated in a 3-week meditation or yoga retreat.",
  "A small business could develop and launch a basic website.",
  "You could have learned to juggle three balls proficiently.",
  "Enough time to read all of Shakespeare's tragedies or comedies.",
  "You could have fostered a shelter animal, helping it transition to a forever home."
];
