export const ubiquityFacts = [
    "You could watch the entire 'Lord of the Rings' trilogy (extended editions) over 11 times.",
    "Fly from New York to Sydney and back about 3 times.",
    "Read 'War and Peace' by Leo Tolstoy (average reader) about 2.5 times.",
    "Learn the basics of a new programming language like Python through an intensive course.",
    "Hike the Inca Trail to Machu Picchu and back, with some rest days.",
    "Complete a 1000-piece jigsaw puzzle... probably about 20 times.",
    "Listen to the complete works of Beethoven.",
    "Binge-watch all seasons of 'Game of Thrones' almost twice.",
    "Drive coast-to-coast across the United States (e.g., from LA to NYC) and have plenty of time for stops.",
    "Knit a couple of sweaters.",
    "Master a few complex recipes and host a grand dinner party.",
    "Complete the main story of the video game 'The Witcher 3: Wild Hunt' and some side quests.",
    "Write a novella of about 30,000 words.",
    "Take a road trip through the entire length of Italy, from the Alps to Sicily.",
    "Build a complex LEGO Technic set, like the Bugatti Chiron.",
    "Learn to play a simple song on the guitar or piano.",
    "Volunteer for a local community project for two full work weeks.",
    "Complete an online certification in a professional skill.",
    "Plant a small vegetable garden and see the first sprouts.",
    "Rewatch all the 'Star Wars' movies (Skywalker saga) about 6 times.",
    "Take a deep dive into a historical topic, reading several books and watching documentaries.",
    "Assemble all the furniture for a new apartment from IKEA.",
    "Create a detailed Dungeons & Dragons campaign from scratch.",
    "Learn enough of a new language on Duolingo to have a basic conversation.",
    "Go on a 5-day meditation retreat.",
    "Edit a feature-length film's worth of vacation footage.",
    "Train for and run a half-marathon, if you have a basic fitness level.",
    "Read the entire 'Harry Potter' series.",
    "Take a short cruise in the Caribbean.",
    "Build a custom PC from scratch, including research and cable management.",
    "Learn the art of making sourdough bread from starter to loaf.",
    "Complete a detailed adult coloring book.",
    "Organize and declutter your entire home, Marie Kondo style.",
    "Watch every single episode of 'The Office' (US).",
    "Take a photography course and practice by taking thousands of photos.",
    "Create a portfolio website for your work.",
    "Go on a multi-day backpacking trip in a national park.",
    "Learn how to do basic car maintenance, like changing oil and tires.",
    "Take a course on financial planning.",
    "Create a family tree going back several generations.",
    "Visit all the major museums in a large city like Paris or London.",
];
